### Numpy Random number
- Random number doesn't mean a different number every time, Random means something that can not be predicted logically.

In [7]:
# simple random number generator
import numpy as np

x = np.random.randint(100, size=10)
print("10 random numpy value within 1000", x)

y = np.random.rand(100)
print(y)

[74 29 54 75 50 95 14 33 27 53]
[5.60815072e-01 8.75392613e-01 2.28358928e-01 6.92235658e-01
 5.63027918e-01 6.93139945e-01 7.08326263e-04 4.77570866e-01
 4.39525135e-01 8.80466390e-01 2.20498945e-02 2.55116857e-01
 3.24237695e-02 9.34036434e-01 7.10153068e-01 9.87255719e-01
 1.16468421e-01 9.76771466e-01 5.32316187e-01 4.46330206e-01
 8.43871491e-01 7.62307714e-01 5.90381515e-01 9.50433854e-02
 1.04646822e-01 8.26439580e-01 3.27217507e-01 6.16222562e-01
 2.34944837e-01 6.65765411e-01 5.71069709e-01 7.56035906e-01
 9.29868629e-01 9.24006428e-01 9.76178054e-01 1.48382491e-01
 8.18658164e-01 4.88204928e-01 8.70265888e-01 3.76424289e-01
 5.08448498e-03 4.41933515e-01 4.97427242e-01 3.00177096e-01
 4.75467670e-01 6.43831926e-01 9.69981549e-01 5.14369483e-02
 3.81950017e-01 2.22364751e-01 1.05288111e-01 1.15866796e-01
 6.03247956e-02 9.43570911e-01 8.18510029e-01 8.86585708e-01
 5.85363492e-01 9.36303795e-01 5.47047113e-01 4.08142766e-01
 1.53991539e-01 8.10168123e-01 7.21171526e-01 1.01164

### Generate 2D array

In [10]:
# (row, column)
x = np.random.randint(100, size=(3,5))
print(x)

[[ 3 70 36 52 55]
 [67 90 20 80  6]
 [78 77 46 21 79]]


### Generate random number from Array

In [11]:
import numpy as np

x = np.random.choice([1,2,3,4,5])
print(x)

1
