### Shape of an Array
The shape of an array is the number of elements in each dimension.


In [1]:
import numpy as np

In [2]:
arr = np.array(0)
print(arr.shape)

()


In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr.shape)

(1, 1, 1, 1, 4)


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_array = arr.reshape(4,3)
print(new_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print("flatten the array", newarr) 

flatten the array [1 2 3 4 5 6]


In [15]:
arr = np.array([1,2,3,4,45])
arr.reshape(5,2)
print(arr)

ValueError: cannot reshape array of size 5 into shape (5,2)