## What is Tensor?
Tensors are data type of data structure used in linear algebra and like vectors and matrix you can calculate arithmetic operation with tensors.
Generally a Tensor is a generalization of vector and matrix is easily understood as a multidimensional array.

In the general case, an array of numbers arranged on a regular grid with a variable
number of axes is known as a tensor.

A Zero dimensional mean o order tensor.
A vector is a one dimensional or first order tensor.
A matrix is a 2nd dimensional or 2nd order tensor.

In [3]:
import numpy as np

In [5]:
# Addition
# define first tensor
A = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

C = A+B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [7]:
# Subtraction
print(A-B)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [9]:
# Multiplication
print(A*B)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [11]:
# Division
print(A/B)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
# Tensor dot product
A = np.array([1,2])
B = np.array([3,4])

C = np.tensordot(A,B)
print(C)

[[3 4]
 [6 8]]
