### Type of Matrix
- Square matrix
   - Row and column are same.
- Symmetric Matrix
   - Top-right triangle is the same as the
bottom-left triangle.
- Triangular Matrix
   - The upper-right or lower-left
of the matrix with the remaining elements filled with zero values.
- Diagonal Matrix
  - The
main diagonal is taken from the top left of the matrix to the bottom right
- Identity Matrix
  - The main diagonal (top-left
to bottom-right) have the value one, while all other values are zero
- Orthogonal Matrix
  - v · w T = 0
### Matrix Operation:
- Transpose
- Inverse
- Trace
- Determinant
- Rank



In [2]:
import numpy as np

In [3]:
# square matrix
square_matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [4]:
#Symmetric Matrix
symmetric_matrix = np.array([
    [1,2,3],
    [2,1,4],
    [4,5,1]
])

In [5]:
#triangular matrix
#upper triangular matrix
upper_triangular_matrix = np.array([
    [1,2,3],
    [0,2,3],
    [0,0,3]
])
# lower triangular matrix
lower_triangular_matrix = np.array([
    [1,0,0],
    [1,2,0],
    [3,4,5]
])

In [6]:
# Diagonal Matrix
diagonal_matrix = np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

In [7]:
# Identity Matrix
I = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

In [3]:
#transpose matrix
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
C = A.T
print(C)

[[1 3 5]
 [2 4 6]]


In [5]:
from numpy.linalg import inv

A = np.array([
    [1.0, 2.0],
    [3.0,4.0]
])
print(A)
# inverse matrix
B = inv(A)
print(B)
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [6]:
# Trace
from numpy import trace
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
# top left to bottom right
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [4]:
# Find determined
from numpy.linalg import det
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [14]:
# rank
from numpy.linalg import matrix_rank

v1 = np.array([1,2,3,4])
print(matrix_rank(v1))
v2 = np.array([
    [1,2,3],
    [3,4,5],
    [33,4,50],
])
print(matrix_rank(v2))

v3 = np.array([
    [1,2],
    [3,4]
])
print(matrix_rank(v3))

1
3
2
