In [16]:
import numpy as np

x = np.ones((3,3), dtype=np.int)
# print(x)
# notice duplicated last dimension [0,1,2.... column index]
y = x[:,[0,1,2,2]]
x[0,0] = 22
print(x)
print(y)

[[22  1  1]
 [ 1  1  1]
 [ 1  1  1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4,5,6],
    [7,8,9]
])
# ["row", column]
x[-1,] = [33, 44, 55]
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [33 44 55]]


In [33]:
import numpy as np

# create an array using arange
x = np.arange(5)
# it creates array value from 0 to 4
print(x)

[0 1 2 3 4]


In [1]:
import numpy as np
from numpy.lib.stride_tricks import as_strided
# overlapped entries
x = np.arange(16)
y = as_strided(x,(7,4),(8,4) )
print(y)

[[          0  4294967296           1  8589934592]
 [          1  8589934592           2 12884901888]
 [          2 12884901888           3 17179869184]
 [          3 17179869184           4 21474836480]
 [          4 21474836480           5 25769803776]
 [          5 25769803776           6 30064771072]
 [          6 30064771072           7 34359738368]]


In [1]:
import numpy as np

arr = [
    [1,2],
    [2,2],
    [6,8],
    [9,8],
    [2,5],
    [8,5],
    [5, None]
]

parent = [x[1] for x in arr]
node = [x[0] for x in arr]
for i in node:
    if i in parent and parent.count(i) > 1:
        print(i, "Inner")
    else:
        print(i, "Leaf")

1 Leaf
2 Inner
6 Leaf
9 Leaf
2 Inner
8 Inner
5 Inner


In [1]:
# Indexing
import numpy as np

x = np.array([
    [1, 2, 3],
    [4,5,6],
    [7,8,9]
])
print(x[0:, -1])

[3 6 9]


In [8]:
# reshape to 1D to 2D
import numpy as np

data = np.array([11,2,3,4,5,6])
print(data.shape[0])
data = data.reshape(data.shape[0], 1)
print(data.shape)

6
(6, 1)


In [11]:
import numpy as np

data = np.array([
    [1, 2],
    [3,4],
    [7,8]
])
data = data.reshape(2, 3)
print(data)

[[1 2 3]
 [4 7 8]]
