In [2]:
import numpy as np
x = np.array([1,2,3], dtype=np.float32)
# show items
# print(x)
# shape of array
print (x.shape)
print(x.size)
# number of byte per item
print(x.itemsize)

(3,)
3
4


In [3]:
import numpy as np

#uniform container means  single data type that is used to store elements in a collection of data
sin_arr = np.sin(np.array([1,2,3], dtype=np.float32))
print(sin_arr)

[0.841471  0.9092974 0.14112  ]


In [4]:
import numpy as np
# find shape  (row, column)
arr = np.array([[1,2,3],[1, 2,4]])
# print(arr.shape)
# print(arr[-1])
# [simple_slicing:, column_number]
print(arr[1:,2])
# first row and last column [simple list operation, column operation]
print(arr[:,::-1])

[4]
[[3 2 1]
 [4 2 1]]


In [1]:
import numpy as np

a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [3]:
# one dimensional list to array
import numpy as np

data = [1,2,3,4,5,5]
a = np.array(data)
print(a)


[1 2 3 4 5 5]


In [ ]:
# Indexing
