In [4]:
import numpy as np
# vertical stack
"""
this means increase row
"""
# create first array
a = np.array([1,2,3])

# create second array
b = np.array([4,5,6])

a3 = np.vstack((a,b,a))
print(a3)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [3]:
import numpy as np
# horizontal stack
"""
increase column
"""
# create first array
a = np.array([1,2,3])

# create second array
b = np.array([4,5,6])

a3 = np.hstack((a,b))
print(a3)

[1 2 3 4 5 6]
