In [2]:
import numpy as np
# create new array, which contain random value
a = np.empty([3,4])
print(a)

[[1.71189399e-316 0.00000000e+000 2.10077583e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]]


In [4]:
import numpy as np
# create a new array which contains zeroes
a = np.zeros([3,4],dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
