### What is vector?
A vector is tuple of one or more values called scalars.
Generally vector represented like: v = (v1, v2, v3)
where v1, v2 and v3 are scalar value often real values. Vector also
represent vertically below like that:
v = (
v1
v2
v3
)
Note: length or magnitude are same in Vector

### What is a Matrix
Matrix is a two-dimensional array of scalars with one or more column and one or more rows.
below the example of matrix:
A = ((1,2,3),(3,4,5))

In [1]:
import numpy as np

In [10]:
a = np.arange(6).reshape((2,3))
b = np.arange(3)
print(a+b)

[[0 2 4]
 [3 5 7]]


In [16]:
# vector norm
from numpy.linalg import norm

a = np.array([1,2,3,10])
# l1 = v1+v2+v3
l1 = norm(a,1)
print(l1)
# l2 = sqrt(v1+v2+v3)
l2 = norm(a,2)
print(l2)

16.0
10.677078252031311


In [18]:
# maximum norm
from math import inf
mx_norm = norm(a, inf)
print(mx_norm)

10.0


In [23]:
a = np.arange(6).reshape((3,2))
b = np.arange(6).reshape((2,3))
print(a)
print(b)
print()

print(a.dot(b))

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
