In [2]:
import numpy as np

## Broadcasting rules
1. Same dimension
2. Size one of the dimension should be 1

In [15]:

a = np.array([5, 7, 3, 1])
b = np.array([90, 50, 0, 30])

# array are compatible because of same Dimension
c = a * b
print(c)

[450 350   0  30]


In [21]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]])
print(c.shape)
# print(a + b) #valid
print(a + c) #invalid


(2, 2, 3)
[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]


In [14]:

a = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
b = np.arange(0).reshape((2,3))
print(a.shape)
print(b.shape)
print(a+b)
# Output: (2, 2, 3)

(2, 2, 3)
(4,)


ValueError: operands could not be broadcast together with shapes (2,2,3) (4,) 