In [2]:
import numpy as np

In [9]:
# https://www.hackerrank.com/challenges/np-arrays/problem
l = [int(x) for x in input().split()]
array = np.array(l, dtype="float64")
rev_arr = np.flip(array)
print(rev_arr)

[]


In [16]:
n = int(input())
m = int(input())
lis = [[int(x) for x in input().split()][:m] for i in range(n)]
array = np.array()

[[1 3 6]
 [2 4 7]]
[1 2 3 4 6 7]


In [33]:
# https://www.hackerrank.com/challenges/np-concatenate/problem
import numpy
n, m, p = [int(x) for x in input().split()]
a1 = numpy.array([[int(x) for x in input().split()][:p] for _ in range(n)])
a2 = numpy.array([[int(x) for x in input().split()][:p] for _ in range(m)])
a1 = [[1,2],
      [1,2],[1,2],[1,2]]
a2 = [[3,4],
      [5,6],[7,8]]
print(a1)
print(a2)

print(numpy.concatenate((a1, a2)))

ValueError: not enough values to unpack (expected 3, got 0)

In [44]:
# https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?h_r=next-challenge&h_v=zen
shape = tuple(int(x) for x in input().split())
print(numpy.zeros(shape, dtype=numpy.int64))
print(numpy.ones(shape,dtype=numpy.int64))


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [58]:
# https://www.hackerrank.com/challenges/np-eye-and-identity/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen
n,m = tuple(int(x) for x in input().split())[:2]
numpy.set_printoptions(legacy="1.13")
print(numpy.eye(n,m))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [61]:
# https://www.hackerrank.com/challenges/np-array-mathematics/problem?h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen
n,m = tuple(int(x) for x in input().split())
A  = numpy.array([[int(x) for x in input().split()][:m] for _ in range(n)])
B  = numpy.array([[int(x) for x in input().split()][:m] for _ in range(n)])
print(numpy.add(A,B))
print(numpy.subtract(A,B))
print(numpy.multiply(A,B))
print(numpy.floor_divide(A,B,))
print(numpy.mod(A,B))
print(numpy.power(A,B))

[[5 7 9]]
[[-3 -3 -3]]
[[ 4 10 18]]
[[ 0.25  0.4   0.5 ]]
[[1 2 3]]
[[1 4 9]]


In [62]:
# https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem
my_array = [1.1,2.2,3.3,4.4,5.5,6.6, 7.7, 8.8, 9.9]
print(numpy.floor(my_array))
print(numpy.ceil(my_array))
print(numpy.rint(my_array))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [66]:
# https://www.hackerrank.com/challenges/np-sum-and-prod/problem
n, m = tuple(int(x) for x in input().split())

array = numpy.array([[int(x) for x in input().split()][:m] for _ in range(n)])
s = numpy.sum(array,axis=0)
print(numpy.product(s))

ValueError: not enough values to unpack (expected 2, got 0)

In [67]:
# https://www.hackerrank.com/challenges/np-min-and-max/problem
n, m = tuple(int(x) for x in input().split())

array = numpy.array([[int(x) for x in input().split()][:m] for _ in range(n)])
m = numpy.min(array, axis=1)
print(numpy.max(m))

ValueError: not enough values to unpack (expected 2, got 0)

In [68]:
# https://www.hackerrank.com/challenges/np-mean-var-and-std/problem
n, m = tuple(int(x) for x in input().split())

array = numpy.array([[int(x) for x in input().split()][:m] for _ in range(n)])
numpy.set_printoptions(legacy="1.13")
print(numpy.mean(array,axis=1))
print(numpy.var(array,axis=0))
print(round((numpy.std(array)), 11))

ValueError: not enough values to unpack (expected 2, got 0)

In [69]:
# https://www.hackerrank.com/challenges/np-dot-and-cross/problem
n = int(input())

a = numpy.array([[int(x) for x in input().split()][:n] for _ in range(n)])
b = numpy.array([[int(x) for x in input().split()][:n] for _ in range(n)])
print(numpy.dot(a,b))

[[ 4 10]
 [18 28]]
